name: Project Board Automation

on:
  pull_request:
    types: [opened, ready_for_review]
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR/Issue to Project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/panckeyk/projects/6
          github-token: ${{ secrets.PROJECT_PAT }}